### ISSUE TITLE
MQ Semaphore is busy

### ISSUE THREAD

**Issue by abudavis** [ibm-messaging/mq-rdqm#1]
If there is a semaphore issue (AMQ6150W: IBM MQ semaphore is busy) on the node the QMGR is running on, QMGR status is "Ending Immediately" with about 3 processes still running (ps –ef). RDQM at this stage does not attempt to failover the QMGR to one of the remaining healthy nodes.

**Comment by john-colgrave** [comment]
This GitHub repository is for samples, unofficial documentation etc. relating to the RDQM feature in IBM MQ and Issues should be limited to issues with the content of this repository or requests for additional content. Possible issues with the IBM MQ product should be raised using the usual support channels.
