### ISSUE TITLE
RDQM : When the network interface on node 3 has a problem.

### ISSUE THREAD

**Issue by abudavis** [ibm-messaging/mq-rdqm#2]
Scenario : Preferred HA node is set to none. QMGR is running on node 1. Node 2 is suspended. Node 3 is active. Now, node 1 gets rebooted , as a result of node 2 being on standby, RDQM tries to start QMGR on remaining node 3. But now, node 3 has a IP interface problem, so its not able to plug the IP onto interface. Meanwhile, Node 1 comes backup and rejoins the cluster but still RDQM is trying to bring up QMGR on Node 3. To snap RDQM out of Node 3, Node 2 was resumed and then RDQM immediately started the QMGR on Node 2. Recommendation : In this scenario, since Node 1 came back up, it should have started the QMGR on Node 1 rather than waiting Node 2 to come online from standby state for failover.

**Comment by john-colgrave** [comment]
This GitHub repository is for samples, unofficial documentation etc. relating to the RDQM feature in IBM MQ and Issues should be limited to issues with the content of this repository or requests for additional content. Possible issues with the IBM MQ product should be raised using the usual support channels.
