### ISSUE TITLE
Status Not Available after HA preference is set from Node 3

### ISSUE THREAD

**Issue by abudavis** [ibm-messaging/mq-rdqm#3]
If the setting of the HA preference to (node1, node 2) is executed on node 3, then dspmq says "Status Not Available" and HA current location is "unknown" across nodes.

**Comment by john-colgrave** [comment]
This GitHub repository is for samples, unofficial documentation etc. relating to the RDQM feature in IBM MQ and Issues should be limited to issues with the content of this repository or requests for additional content. Possible issues with the IBM MQ product should be raised using the usual support channels.
