### ISSUE TITLE
RDQM multi-Datacenter implementation questions

### ISSUE THREAD

**Issue by Sandeep17jy** [ibm-messaging/mq-rdqm#5]
RDQM has adapted pacemaker and DRBD implementations in MQ v9.0.4  , have some questions on the pacemaker functionalities across multi-datacenter implementation 
 
1)      “ The floating address binds to a named physical interface on the primary node for the RDQM “ Will the Pacemaker be responsible to move the floating IP address to a node on secondary datacenter. 
2)      Is there any specific requirements on layer 2 cisco network implementation across two datacenters ? 
3)      Is there any specific DRBD  requirements for cross datacenter data replication.
4) If both datacenters subnets are different is there a alternative way/configurations to implement RDQM work ?

**Comment by john-colgrave** [comment]
The current HA support in RDQM is aimed at a single datacenter but it is possible to use it between datacenters if the network between the datacenters is suitable, which primarily means reliable and of low (< 5 ms) latency.

To answer your specific questions:

1. If the network between datacenters supports the floating IP feature (see the next answer for details) then yes, Pacemaker will move the floating IP address if the relevant RDQM moves.

2. Each node has to have an interface with the name of the interface used to declare the floating IP address and the static IP addresses for that interface on each of the three nodes have to be in the same subnet. The floating IP address and the static IP addresses have to be in the same subnet.

3. This is mainly the latency requirement.

4. You can use RDQM without the floating IP feature.
